export const DRINKS = [
  {
    id: 7,
    title: "Smirnoff vodka Blue Label",
    image: "/smirnoffvodkabluelabel.jpg",
    price: 700,
    type: "vodka",
  },
  {
    id: 1,
    title: "Hennesy",
    image: "/hennessy.png",
    price: 600,
    type: "wine",
  },
  {
    id: 2,
    title: "Scotch Wiskey",
    image: "/hennessyblack.webp",
    price: 300,
    type: "scotch",
  },
  {
    id: 3,
    title: "Champagne",
    price: 900,
    type: "Champagne",
    image: "/hennessyclassivm.webp",
  },
  {
    id: 4,
    title: "Azule Tequila",
    image: "/azuletequila.png",
    price: 600,
    type: "tequila",
  },
  {
    id: 5,
    title: "Jack Daniels",
    image: "/jackdaniels.jpg",
    price: 300,
    type: "scotch",
  },
  {
    id: 6,
    title: "James Hennessy",
    price: 900,
    type: "spirit",
    image: "/james_hennessy.webp",
  },
];
