import Head from "next/head";
import Image from "next/image";
import {
  Box,
  Button,
  Center,
  Text,
  Flex,
  useRadioGroup,
  Heading,
} from "@chakra-ui/react";
import NextLink from "next/link";
import { HomeSlider } from "../component/carousel/slider.carousel";
import { Selector } from "../component/selector";
import { Header } from "../infrastructure/navigation/header.navigation";
import styles from "../styles/Home.module.css";
import { Drinks } from "../component/drinks";
import { IDrink } from "../@types/drink";
import { Footer } from "../infrastructure/navigation/footer.navigaton";
import { RadioCard } from "../component/radio-card";
import { DRINK_TYPES } from "../utilities/drink-types.utilities";

export default function Home() {
  const drinks: IDrink[] = [
    {
      title: "hennesy",
      image: "/hennessy.png",
      price: 600,
      type: "Scotch",
    },
    {
      title: "Scotch Wiskey",
      image: "/hennessyblack.webp",
      price: 300,
      type: "Scotch",
    },
    {
      title: "Champagne",
      price: 900,
      type: "Champagne",
      image: "/hennessyclassivm.webp",
    },
    {
      title: "Scotch Wiskey",
      image: "/hennessypurewhite.webp",
      price: 600,
      type: "Scotch",
    },
    {
      title: "Jack Daniels",
      image: "/jackdaniels.jpg",
      price: 300,
      type: "Scotch",
    },
    {
      title: "James Hennessy",
      price: 900,
      type: "Champagne",
      image: "/james_hennessy.webp",
    },
  ];

  const handleChange = (e: any) => {
    console.log(e);
  };
  const options = DRINK_TYPES;

  const { getRootProps, getRadioProps } = useRadioGroup({
    name: "propertyType",
    defaultValue: "Buy",
    onChange: handleChange,
  });

  const group = getRootProps();

  return (
    <div className={styles.container}>
      <Head>
        <title>Cella</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>

      <main className={styles.main}>
        <Selector />
        <Box
          h={{ base: "10rem", md: "20rem", lg: "25rem" }}
          w="100%"
          overflow={"hidden"}
        >
          <HomeSlider />
        </Box>
        <Box my="2rem">
          <Center pos="relative">
            <Image
              src="/arrowleft.png"
              alt="arrow left"
              width={100}
              height={100}
            />
            <Heading
              color="brand.400"
              fontSize={"1.8rem"}
              textTransform="uppercase"
              fontWeight={500}
              mx="1rem"
            >
              Best Sellers
            </Heading>
            <Image
              src="/arrowright.png"
              alt="arrow right"
              width={100}
              height={100}
            />
          </Center>
          <Center>
            <Text color="brand.200" fontWeight={500}>
              Below are our clients top choices and you may choose from any
            </Text>
          </Center>
          <Drinks drinks={drinks} />
          <Center>
            <NextLink passHref href="/">
              <Button
                color="brand.600"
                bg="brand.300"
                _hover={{
                  bg: "brand.400",
                  color: "brand.500",
                }}
              >
                View More
              </Button>
            </NextLink>
          </Center>
        </Box>

        <Box my="2rem">
          <Center mb="1rem">
            <Image
              src="/arrowleft.png"
              alt="arrow left"
              width={100}
              height={100}
            />
            <Heading
              color="brand.400"
              fontSize={"1.8rem"}
              textTransform="uppercase"
              fontWeight={500}
              mx="1rem"
            >
              Shop Here
            </Heading>
            <Image
              src="/arrowright.png"
              alt="arrow right"
              width={100}
              height={100}
            />
          </Center>
          <Flex
            {...group}
            py={{ base: ".2rem", md: ".3rem", lg: ".4rem" }}
            gap={{ base: 1, md: 1, lg: 1 }}
            w="100%"
            flexWrap={"wrap"}
            alignItems={{ base: "center" }}
            justify={{ base: "center", md: "center", lg: "center" }}
          >
            {options.map((value) => {
              const radio = getRadioProps({ value });
              return (
                <RadioCard key={value} {...radio}>
                  {value}
                </RadioCard>
              );
            })}
          </Flex>
          <Drinks drinks={drinks} />
          <Center>
            <NextLink passHref href="/">
              <Button
                color="brand.600"
                bg="brand.300"
                _hover={{
                  bg: "brand.400",
                  color: "brand.500",
                }}
              >
                View More
              </Button>
            </NextLink>
          </Center>
        </Box>
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
