import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import {
  Box,
  Button,
  Center,
  Text,
  Flex,
  useRadioGroup,
  Heading,
  useMediaQuery,
} from "@chakra-ui/react";
import { useState, useEffect } from "react";
import NextLink from "next/link";
import { HomeSlider } from "../component/carousel/slider.carousel";
import { Selector } from "../component/selector";
import { Header } from "../infrastructure/navigation/header.navigation";
import { Drinks } from "../component/drinks";
import { IDrink } from "../@types/drink";
import { Footer } from "../infrastructure/navigation/footer.navigaton";
import { RadioCard } from "../component/radio-card";
import { DRINK_TYPES } from "../utilities/drink-types.utilities";
import DRINKS from "../infrastructure/data/wines.json";
import BestSellers from "../infrastructure/data/best-sellers.json";

export default function Home() {
  const [isMobile] = useMediaQuery("(max-width: 600px)");

  const [data, setData] = useState<IDrink[]>([]);

  const handleChange = (e: any) => {
    let term = e && e.toLowerCase();
    const item = DRINKS.filter((drinks) => drinks.type === term);
    setData(item);
  };
  const options = DRINK_TYPES;

  const { getRootProps, getRadioProps } = useRadioGroup({
    name: "tags",
    defaultValue: "Scotch",
    onChange: handleChange,
  });

  const group = getRootProps();

  const handleSearch = (e: any) => {
    let term = e && e.innerText.toLowerCase();
    const item = DRINKS.filter((drinks) => drinks.type === term);
    setData(item);
  };

  useEffect(() => {
    setData(DRINKS);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Cella</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>

      <main className={styles.main}>
        <Selector onChange={handleSearch} />
        <Box
          h={{ base: "20rem", md: "20rem", lg: "25rem" }}
          w={{ base: "100%", md: "100%" }}
          overflow={"hidden"}
          m="auto"
        >
          <HomeSlider />
        </Box>
        <Box my="2rem">
          <Center pos="relative">
            <Image
              src="/arrowleft.png"
              alt="arrow left"
              width={isMobile ? 50 : 100}
              height={isMobile ? 50 : 100}
            />
            <Heading
              color="brand.400"
              fontSize={{ base: "1rem", md: "1.8rem" }}
              textTransform="uppercase"
              fontWeight={500}
              mx="1rem"
            >
              Best Sellers
            </Heading>
            <Image
              src="/arrowright.png"
              alt="arrow right"
              width={isMobile ? 50 : 100}
              height={isMobile ? 50 : 100}
            />
          </Center>
          <Center>
            <Text
              color="brand.200"
              fontWeight={500}
              px={{ base: "2rem", md: "1rem" }}
            >
              Below are our clients top choices and you may choose from any
            </Text>
          </Center>
          <Drinks drinks={BestSellers} />
          <Center>
            <NextLink passHref href="/">
              <Button
                color="brand.600"
                bg="brand.300"
                _hover={{
                  bg: "brand.400",
                  color: "brand.500",
                }}
              >
                View More
              </Button>
            </NextLink>
          </Center>
        </Box>

        <Box my="2rem">
          <Center mb="1rem">
            <Image
              src="/arrowleft.png"
              alt="arrow left"
              width={isMobile ? 50 : 100}
              height={isMobile ? 50 : 100}
            />
            <Heading
              color="brand.400"
              fontSize={{ base: "1rem", md: "1.8rem" }}
              textTransform="uppercase"
              fontWeight={500}
              mx="1rem"
            >
              Shop Here
            </Heading>
            <Image
              src="/arrowright.png"
              alt="arrow right"
              width={isMobile ? 50 : 100}
              height={isMobile ? 50 : 100}
            />
          </Center>
          <Flex
            {...group}
            py={{ base: ".2rem", md: ".3rem", lg: ".4rem" }}
            px="1rem"
            gap={{ base: 1, md: 1, lg: 1 }}
            w="100%"
            alignItems={{ base: "center" }}
            overflow="auto"
          >
            {options.map((value) => {
              const radio = getRadioProps({ value });
              return (
                <RadioCard key={value} {...radio}>
                  {value}
                </RadioCard>
              );
            })}
          </Flex>
          <Drinks drinks={data} />
          <Center>
            <NextLink passHref href="/shop">
              <Button
                color="brand.600"
                bg="brand.300"
                _hover={{
                  bg: "brand.400",
                  color: "brand.500",
                }}
              >
                View More
              </Button>
            </NextLink>
          </Center>
        </Box>
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  );
}
